# Generated by Django 3.1.4 on 2020-12-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact_number',
            field=models.IntegerField(max_length=12, unique=True),
        ),
    ]
